name:                matlog-formulas
version:             0.1.0.0
github:              "githubuser/matlog-formulas"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/matlog-formulas#readme>

dependencies:
- base >= 4.7 && < 5
- random
- containers

library:
  source-dirs: src

executables:
  hw1:
    main:                Main.hs
    source-dirs:         app/hw1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matlog-formulas
  hw2:
    main:                Main.hs
    source-dirs:         app/hw2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matlog-formulas
    - process

tests:
  randomized-tests:
    main:                Spec.hs
    source-dirs:         test/randomized
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matlog-formulas
    - QuickCheck

  unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matlog-formulas
    - HUnit
